config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  root 'static_pages#index'

  get '/help',     to: 'static_pages#help'

  get 'signup',   to: 'users#new'

  get '/login',   to: 'sessions#new'

  post '/login',   to: 'sessions#create'

  delete '/logout',  to: 'sessions#destroy'

  resources :users


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  attr_accessor :remember_token

  before_save { self.email = email.downcase}

  validates :first_name, presence: true, length: { minimum: 2, maximum: 30}
  validates :last_name, presence: true, length: { minimum: 2, maximum: 30}

  VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {minimum: 10, maximum: 50}, format: { with: VALID_EMAIL_REGEX},
            uniqueness: { case_sensitive: false}

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # Returns a random toker
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Return a digest_token of a given string
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Remembers a user token in the database for persistent sessions

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end


  # Returns true if the given token matches the digest
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create

    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to user
      flash[:primary] = "You're now logged in!"
    else
      flash.now[:alert] = 'Invalid credentials. Pleasse try again'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    flash[:primary] = 'Bye, See you soon!'
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user, only: [:edit, :update]

  def index
    
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      flash[:success] = 'User created successfully'
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = 'Profile updated successfuly'
      redirect_to @user
    else
      render 'edit'
    end
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def logged_in_user
    unless logged_in?
      flash[:alert] = 'Pleasse log in'
      redirect_to login_url
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to root_url unless @user == current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Log in the given user
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remember a user in a permanent session

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns the user corresponding to the remember token cookie

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
    if user && user.authenticated?(cookies[:remember_token])
      log_in user
      @current_user = user
    end
    end
  end



  # Returs true if user logged in, otherwise false
  def logged_in?
    !current_user.nil?
  end

  # Forget a persistent session
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end



  # Logs out the current user
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.last_name)
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="row small-up-1 medium-up-3">
    <div class="column">
      <h4>Contact Info</h4>
      <hr>
      <a href="#"><span>Phone:</span>55 5555 5555</a>
      <a href="#"><span>Email:</span>info@company.com</a>
      <a href="#"><span>Address:</span> 123 Center Street</a>
    </div>

    <div class="column">
      <h4>Site Map</h4>
      <hr>
      <a href="#">About Us</a>
      <a href="#">Services</a>
      <a href="#">Contact Us</a>
    </div>
    <div class="column">
      <h4>Social Media</h4>
      <hr>
      <a href="#">Facebook</a>
      <a href="#">Twitter</a>
      <a href="#">Instagram</a>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<div class="title-bar" data-responsive-toggle="responsive-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle="responsive-menu"></button>
  <div class="title-bar-title">Menu</div>
</div>

<div class="top-bar" id="responsive-menu">
  <div class="top-bar-left">
    <ul class="menu">
      <li class="menu-text">Authentication App</li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="dropdown menu" data-dropdown-menu>
      <li><%= link_to 'Home', root_path %></li>
      <li><%= link_to 'Help', help_path %></li>

      <% if logged_in? %>
        <li><%= link_to 'users', '#' %></li>

      <li class="has-submenu">
        <a href="#0">Account</a>
        <ul class="submenu menu vertical" data-submenu>
          <li><%= link_to 'Profile', current_user %></li>
          <li><%= link_to 'Settings', edit_user_path(current_user) %></li>
          <li><%= link_to 'Log Out', logout_path, method: 'delete' %></li>
        </ul>
      </li>
      <% else %>
        <li><%= link_to 'Log In', login_path %></li>
      <% end %>
    </ul>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

  <div class="content">

  <%= render 'layouts/navbar' %>

    <%= render 'shared/flash_messages' %>

    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% if flash[:success] %>
  <div class="success callout" data-closable>
    <%= display_flash_messages %>
    <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <% elsif flash[:alert] %>
  <div class="alert callout" data-closable>
    <%= display_flash_messages %>
    <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <% elsif flash[:primary] %>
  <div class="primary callout" data-closable>
    <%= display_flash_messages %>
    <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

<% end %>

app/views/static_pages/help.html.erb
<div class="row">
  <div class="small-12 medium-12 large-12 columns">
    <h1 class="title">Help Page</h1>
  </div>
</div>

app/views/static_pages/index.html.erb
<div class="row">
  <div class="small-12 medium-12 large-12 columns">
    <h1 class="title">Welcome to the authentication app</h1>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>


  <%= f.text_field :first_name %>

  <%= f.text_field :last_name %>

  <%= f.email_field :email %>

  <%= f.password_field :password %>

  <%= f.password_field :password_confirmation %>

  <%= f.submit yield(:button_text), class: 'expanded button' %>


<%end%>

app/views/users/edit.html.erb
<%= provide(:title, 'Edit User') %>
<%= provide(:button_text, 'Save your changes') %>

<div class="row">
  <div class="small-10 small-centered medium-4 medium-centered columns">
    <h2 id="sign_up">Update your profile</h2>

    <%= render 'form' %>

    <div class="gravatar_edit">

      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="blank" rel="noopener">change</a>

    </div>

  </div>
</div>

app/views/users/index.html.erb
<h1>Index user</h1>

app/views/users/new.html.erb
<%= provide(:title, 'Sign Up') %>
<%= provide(:button_text, 'Create my account') %>

<div class="row">
  <div class="small-10 small-centered medium-4 medium-centered columns">
    <h2 id="sign_up">Sign Up</h2>

    <%= render 'form' %>

  </div>
</div>

app/views/users/show.html.erb
<%= provide(:title, @user.last_name) %>

<div class="row">
  <div class="small-12 medium-12 columns">
    <h1 class="title">
    <%= gravatar_for @user %>
    <%= @user.first_name + ' ' + @user.last_name %>
    </h1>
  </div>

</div>